#define CIRCLE_DISTANCE 10.0
#define CIRCLE_SIZE_MIN 0.3
#define CIRCLE_SIZE_MAX 0.6

#define ANIM_DURATION 20.0
#define DOT_ANIM_SPEED 2.0
#define DOT_COLOR_BASE ivec3(169, 62, 255)
#define BG_COLOR ivec3(0,0,0)

#define HEADER_COLOR ivec3(200,200,200)
#define HEADER_HEIGHT 100.
#define HEADER_LINE_MARGIN 50.
#define HEADER_LINE_THICKNESS 3.

#define GLOBAL_MARGIN vec2(100., 50.)

#define PODIUM_ANIMATION_OFFSET 100.
#define PODIUM_COLUMN_GAP 100.

#define PODIUM_PADDING vec2(50.)
#define PODIUM_IMAGE_HEIGHT 300.
#define PODIUM_IMAGE_NAME_GAP 20.
#define PODIUM_NAME_BADGE_GAP 0.
#define PODIUM_BADGE_HEIGHT 80.
#define PODIUM_BADGE_GAP 20.
#define PODIUM_BADGE_POSITION_GAP 30.

#define CONSTRUCTOR_ENTRY_HEIGHT 40.

#define CALENDAR_ENTRY_HEIGHT 40.
#define CALENDAR_ENTRY_HEIGHT_EXPANDED 80.
#define CALENDAR_ANIMATION_OFFSET 100.
#define CALENDAR_SHORT_DATE_OFFSET 320.
#define CALENDAR_SHORT_TIME_OFFSET 80.